In [20]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix  
from sklearn.metrics import accuracy_score

In [21]:
# Importing the dataset
dataset = pd.read_csv(r'path of file')
dataset.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

# Summary of dataset

In [22]:
print(dataset.shape)

(150, 5)


In [23]:
# more info on the data
print(dataset.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal_length    150 non-null float64
sepal_width     150 non-null float64
petal_length    150 non-null float64
petal_width     150 non-null float64
species         150 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB
None


In [24]:
# descriptions
print(dataset.describe())

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000


In [25]:
# class distribution
print(dataset.groupby('species').size())

species
setosa        50
versicolor    50
virginica     50
dtype: int64


In [26]:
#split featuers and labels of class
Featuers = dataset.iloc[:, :-1].values
target_class = dataset.iloc[:, -1].values

In [27]:
# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(Featuers, target_class, test_size = 0.2, random_state = 0)

In [28]:
# Decision Tree's

classifier = DecisionTreeClassifier()

classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

In [36]:
cm = confusion_matrix(y_test, y_pred)  

print('Accuracy ' + str(accuracy_score(y_test, y_pred)*100))
print ("Train Accuracy :: ", (accuracy_score(y_train, classifier.predict(X_train))*100))
print ("Test Accuracy ", accuracy_score(y_test, y_pred)*100)
print ("Conusion matrix \n", confusion_matrix(y_test, y_pred))

Accuracy 100.0
Train Accuracy ::  100.0
Test Accuracy  100.0
Conusion matrix 
 [[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
